export const NATIONALITY_TO_ISO: Record<string, string> = {
  "Australian": "au",
  "New Zealander": "nz",
  "British": "gb",
  "German": "de",
  "Dutch": "nl",
  "French": "fr",
  "Spanish": "es",
  "Finnish": "fi",
  "Italian": "it",
  "Canadian": "ca",
  "American": "us",
  "Mexican": "mx",
  "Japanese": "jp",
  "Danish": "dk",
  "Monegasque": "mc",
  "Brazilian": "br",
  "Argentine": "ar",
  "Thai": "th",
  "Chinese": "cn",
  "Polish": "pl",
  "Russian": "ru",
  "Austrian": "at",
  "Swiss": "ch"
};

export const COUNTRY_TO_ISO: Record<string, string> = {
  "Australia": "au",
  "China": "cn",
  "Japan": "jp",
  "Bahrain": "bh",
  "Saudi Arabia": "sa",
  "United States": "us",
  "Italy": "it",
  "Monaco": "mc",
  "Spain": "es",
  "Canada": "ca",
  "Austria": "at",
  "United Kingdom": "gb",
  "Belgium": "be",
  "Hungary": "hu",
  "Netherlands": "nl",
  "Azerbaijan": "az",
  "Singapore": "sg",
  "Mexico": "mx",
  "Brazil": "br",
  "Qatar": "qa",
  "United Arab Emirates": "ae",
  "Abu Dhabi": "ae",
  "France": "fr",
  "Great Britain": "gb"
};

